// <auto-generated />
using System;
using GolAhora.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AppContext = GolAhora.Data.AppContext;

#nullable disable

namespace GolAhora.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20260605182240_MigracionFinal")]
    partial class MigracionFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GolAhora.Models.AdminProfile", b =>
                {
                    b.Property<int>("idAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAdmin"));

                    b.Property<int>("accessLevel")
                        .HasColumnType("int");

                    b.Property<int>("idPersonalClub")
                        .HasColumnType("int");

                    b.HasKey("idAdmin");

                    b.HasIndex("idPersonalClub")
                        .IsUnique();

                    b.ToTable("AdminProfiles");
                });

            modelBuilder.Entity("GolAhora.Models.Assistance", b =>
                {
                    b.Property<int>("idAssistance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAssistance"));

                    b.Property<int>("classId")
                        .HasColumnType("int");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isAssisted")
                        .HasColumnType("bit");

                    b.Property<string>("observations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idAssistance");

                    b.HasIndex("classId");

                    b.HasIndex("clientId");

                    b.ToTable("Assistances");
                });

            modelBuilder.Entity("GolAhora.Models.Certification", b =>
                {
                    b.Property<int>("idCertification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCertification"));

                    b.Property<DateTime>("dateObtained")
                        .HasColumnType("datetime2");

                    b.Property<string>("institution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numberCertificate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("professorId")
                        .HasColumnType("int");

                    b.Property<bool>("verified")
                        .HasColumnType("bit");

                    b.Property<string>("verifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCertification");

                    b.HasIndex("professorId");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("GolAhora.Models.Class", b =>
                {
                    b.Property<int>("idClass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idClass"));

                    b.Property<int>("capacityMax")
                        .HasColumnType("int");

                    b.Property<string>("classType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("courtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int>("profesorId")
                        .HasColumnType("int");

                    b.HasKey("idClass");

                    b.HasIndex("courtId");

                    b.HasIndex("profesorId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("GolAhora.Models.ClientProfile", b =>
                {
                    b.Property<int>("idClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idClient"));

                    b.Property<int?>("ClassidClass")
                        .HasColumnType("int");

                    b.Property<int?>("idTeam")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<int>("numberPartner")
                        .HasColumnType("int");

                    b.HasKey("idClient");

                    b.HasIndex("ClassidClass");

                    b.HasIndex("idTeam");

                    b.HasIndex("idUser")
                        .IsUnique();

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("GolAhora.Models.Competence", b =>
                {
                    b.Property<int>("idCompetence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCompetence"));

                    b.Property<int>("capacityTeams")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regulations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("idCompetence");

                    b.ToTable("Competences", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GolAhora.Models.CompetenceTeam", b =>
                {
                    b.Property<int>("idCompetence")
                        .HasColumnType("int");

                    b.Property<int>("idTeam")
                        .HasColumnType("int");

                    b.Property<int>("idPayment")
                        .HasColumnType("int");

                    b.Property<DateTime>("inscription")
                        .HasColumnType("datetime2");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("idCompetence", "idTeam");

                    b.HasIndex("idPayment");

                    b.HasIndex("idTeam");

                    b.ToTable("CompetenceTeams");
                });

            modelBuilder.Entity("GolAhora.Models.Court", b =>
                {
                    b.Property<int>("idCourt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCourt"));

                    b.Property<int>("courtTypeId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCourt");

                    b.HasIndex("courtTypeId");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("GolAhora.Models.CourtType", b =>
                {
                    b.Property<int>("idTypeCourt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTypeCourt"));

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("pricePerHour")
                        .HasColumnType("float");

                    b.Property<double>("superficie")
                        .HasColumnType("float");

                    b.HasKey("idTypeCourt");

                    b.ToTable("CourtTypes");
                });

            modelBuilder.Entity("GolAhora.Models.Discounts", b =>
                {
                    b.Property<int>("idDiscount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDiscount"));

                    b.Property<string>("conditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("discountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("discountValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("idDiscount");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("GolAhora.Models.Disponibility", b =>
                {
                    b.Property<int>("idDisponibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDisponibility"));

                    b.Property<int>("courtId")
                        .HasColumnType("int");

                    b.Property<int>("day")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("endTime")
                        .HasColumnType("time");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("startTime")
                        .HasColumnType("time");

                    b.HasKey("idDisponibility");

                    b.HasIndex("courtId");

                    b.ToTable("Disponibilities");
                });

            modelBuilder.Entity("GolAhora.Models.EmployeeProfile", b =>
                {
                    b.Property<int>("idEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEmployee"));

                    b.Property<int>("idPersonalClub")
                        .HasColumnType("int");

                    b.Property<string>("sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEmployee");

                    b.HasIndex("idPersonalClub")
                        .IsUnique();

                    b.ToTable("EmployeeProfiles");
                });

            modelBuilder.Entity("GolAhora.Models.Match", b =>
                {
                    b.Property<int>("idMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMatch"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCompetence")
                        .HasColumnType("int");

                    b.Property<int>("idCourt")
                        .HasColumnType("int");

                    b.Property<int>("idResults")
                        .HasColumnType("int");

                    b.Property<int>("idTeamA")
                        .HasColumnType("int");

                    b.Property<int>("idTeamB")
                        .HasColumnType("int");

                    b.Property<bool>("isPlayed")
                        .HasColumnType("bit");

                    b.Property<int>("round")
                        .HasColumnType("int");

                    b.HasKey("idMatch");

                    b.HasIndex("idCompetence");

                    b.HasIndex("idCourt");

                    b.HasIndex("idTeamA");

                    b.HasIndex("idTeamB");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("GolAhora.Models.Payments", b =>
                {
                    b.Property<int>("idPayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPayment"));

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<int>("idClient")
                        .HasColumnType("int");

                    b.Property<int?>("idDiscount")
                        .HasColumnType("int");

                    b.Property<bool>("isSuccessful")
                        .HasColumnType("bit");

                    b.Property<DateTime>("paymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPayment");

                    b.HasIndex("idClient");

                    b.HasIndex("idDiscount");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("GolAhora.Models.PersonalClubProfile", b =>
                {
                    b.Property<int>("idPersonalClub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPersonalClub"));

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<string>("legajo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPersonalClub");

                    b.HasIndex("idUser")
                        .IsUnique();

                    b.ToTable("PersonalClubProfiles");
                });

            modelBuilder.Entity("GolAhora.Models.ProfessorProfile", b =>
                {
                    b.Property<int>("idProfessor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProfessor"));

                    b.Property<string>("certification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idPersonalClub")
                        .HasColumnType("int");

                    b.Property<string>("speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idProfessor");

                    b.HasIndex("idPersonalClub")
                        .IsUnique();

                    b.ToTable("ProfessorProfiles");
                });

            modelBuilder.Entity("GolAhora.Models.Receipts", b =>
                {
                    b.Property<int>("idReceipt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idReceipt"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idPayment")
                        .HasColumnType("int");

                    b.Property<string>("receiptNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("totalAmount")
                        .HasColumnType("float");

                    b.HasKey("idReceipt");

                    b.HasIndex("idPayment")
                        .IsUnique();

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("GolAhora.Models.Reports", b =>
                {
                    b.Property<int>("idReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idReport"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("from")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("generatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("idAdmin")
                        .HasColumnType("int");

                    b.Property<string>("tittle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("to")
                        .HasColumnType("datetime2");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idReport");

                    b.HasIndex("idAdmin");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("GolAhora.Models.Reservation", b =>
                {
                    b.Property<int>("idReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idReservation"));

                    b.Property<TimeSpan>("endTime")
                        .HasColumnType("time");

                    b.Property<int>("idClient")
                        .HasColumnType("int");

                    b.Property<int>("idCourt")
                        .HasColumnType("int");

                    b.Property<int>("idPayment")
                        .HasColumnType("int");

                    b.Property<bool>("isPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("reservationDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("startTime")
                        .HasColumnType("time");

                    b.Property<double>("totalPrice")
                        .HasColumnType("float");

                    b.HasKey("idReservation");

                    b.HasIndex("idClient");

                    b.HasIndex("idCourt");

                    b.HasIndex("idPayment")
                        .IsUnique();

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("GolAhora.Models.Result", b =>
                {
                    b.Property<int>("idResults")
                        .HasColumnType("int");

                    b.Property<int>("idMatch")
                        .HasColumnType("int");

                    b.Property<int>("scoreTeamLocal")
                        .HasColumnType("int");

                    b.Property<int>("scoreTeamVisitor")
                        .HasColumnType("int");

                    b.HasKey("idResults");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("GolAhora.Models.Team", b =>
                {
                    b.Property<int>("idTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTeam"));

                    b.Property<int?>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTeam");

                    b.HasIndex("clientId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("GolAhora.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("registerDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "client-role",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "personal-club-role",
                            Name = "PersonalClubProfile",
                            NormalizedName = "PERSONALCLUBPROFILE"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "admin-role",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "employee-role",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = 5,
                            ConcurrencyStamp = "professor-role",
                            Name = "Professor",
                            NormalizedName = "PROFESSOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GolAhora.Models.League", b =>
                {
                    b.HasBaseType("GolAhora.Models.Competence");

                    b.Property<int>("idLeague")
                        .HasColumnType("int");

                    b.ToTable("Leagues", (string)null);
                });

            modelBuilder.Entity("GolAhora.Models.Tournament", b =>
                {
                    b.HasBaseType("GolAhora.Models.Competence");

                    b.Property<int>("idTournament")
                        .HasColumnType("int");

                    b.ToTable("Tournaments", (string)null);
                });

            modelBuilder.Entity("GolAhora.Models.AdminProfile", b =>
                {
                    b.HasOne("GolAhora.Models.PersonalClubProfile", "personalClubProfile")
                        .WithOne("adminProfile")
                        .HasForeignKey("GolAhora.Models.AdminProfile", "idPersonalClub")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("personalClubProfile");
                });

            modelBuilder.Entity("GolAhora.Models.Assistance", b =>
                {
                    b.HasOne("GolAhora.Models.Class", "clas")
                        .WithMany("assistances")
                        .HasForeignKey("classId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolAhora.Models.ClientProfile", "client")
                        .WithMany("assistances")
                        .HasForeignKey("clientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("clas");

                    b.Navigation("client");
                });

            modelBuilder.Entity("GolAhora.Models.Certification", b =>
                {
                    b.HasOne("GolAhora.Models.ProfessorProfile", "professor")
                        .WithMany("certifications")
                        .HasForeignKey("professorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("professor");
                });

            modelBuilder.Entity("GolAhora.Models.Class", b =>
                {
                    b.HasOne("GolAhora.Models.Court", "court")
                        .WithMany("classes")
                        .HasForeignKey("courtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolAhora.Models.ProfessorProfile", "profesor")
                        .WithMany("classes")
                        .HasForeignKey("profesorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("court");

                    b.Navigation("profesor");
                });

            modelBuilder.Entity("GolAhora.Models.ClientProfile", b =>
                {
                    b.HasOne("GolAhora.Models.Class", null)
                        .WithMany("clients")
                        .HasForeignKey("ClassidClass");

                    b.HasOne("GolAhora.Models.Team", "team")
                        .WithMany("players")
                        .HasForeignKey("idTeam")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GolAhora.Models.User", "user")
                        .WithOne("clientProfile")
                        .HasForeignKey("GolAhora.Models.ClientProfile", "idUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("team");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GolAhora.Models.CompetenceTeam", b =>
                {
                    b.HasOne("GolAhora.Models.Competence", "competence")
                        .WithMany("teams")
                        .HasForeignKey("idCompetence")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolAhora.Models.Payments", "payments")
                        .WithMany("competenceTeams")
                        .HasForeignKey("idPayment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolAhora.Models.Team", "team")
                        .WithMany("competences")
                        .HasForeignKey("idTeam")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("competence");

                    b.Navigation("payments");

                    b.Navigation("team");
                });

            modelBuilder.Entity("GolAhora.Models.Court", b =>
                {
                    b.HasOne("GolAhora.Models.CourtType", "courtType")
                        .WithMany("courts")
                        .HasForeignKey("courtTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("courtType");
                });

            modelBuilder.Entity("GolAhora.Models.Disponibility", b =>
                {
                    b.HasOne("GolAhora.Models.Court", "court")
                        .WithMany("disponibilities")
                        .HasForeignKey("courtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("court");
                });

            modelBuilder.Entity("GolAhora.Models.EmployeeProfile", b =>
                {
                    b.HasOne("GolAhora.Models.PersonalClubProfile", "personalClubProfile")
                        .WithOne("employeeProfile")
                        .HasForeignKey("GolAhora.Models.EmployeeProfile", "idPersonalClub")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("personalClubProfile");
                });

            modelBuilder.Entity("GolAhora.Models.Match", b =>
                {
                    b.HasOne("GolAhora.Models.Competence", "competence")
                        .WithMany("games")
                        .HasForeignKey("idCompetence")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolAhora.Models.Court", "court")
                        .WithMany("matches")
                        .HasForeignKey("idCourt")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolAhora.Models.Team", "teamA")
                        .WithMany("localMatches")
                        .HasForeignKey("idTeamA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolAhora.Models.Team", "teamB")
                        .WithMany("visitorMatches")
                        .HasForeignKey("idTeamB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("competence");

                    b.Navigation("court");

                    b.Navigation("teamA");

                    b.Navigation("teamB");
                });

            modelBuilder.Entity("GolAhora.Models.Payments", b =>
                {
                    b.HasOne("GolAhora.Models.ClientProfile", "client")
                        .WithMany("payments")
                        .HasForeignKey("idClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolAhora.Models.Discounts", "discount")
                        .WithMany("payments")
                        .HasForeignKey("idDiscount")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("client");

                    b.Navigation("discount");
                });

            modelBuilder.Entity("GolAhora.Models.PersonalClubProfile", b =>
                {
                    b.HasOne("GolAhora.Models.User", "user")
                        .WithOne("personalClubProfile")
                        .HasForeignKey("GolAhora.Models.PersonalClubProfile", "idUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("GolAhora.Models.ProfessorProfile", b =>
                {
                    b.HasOne("GolAhora.Models.PersonalClubProfile", "personalClubProfile")
                        .WithOne("professorProfile")
                        .HasForeignKey("GolAhora.Models.ProfessorProfile", "idPersonalClub")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("personalClubProfile");
                });

            modelBuilder.Entity("GolAhora.Models.Receipts", b =>
                {
                    b.HasOne("GolAhora.Models.Payments", "payment")
                        .WithOne("receipt")
                        .HasForeignKey("GolAhora.Models.Receipts", "idPayment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("payment");
                });

            modelBuilder.Entity("GolAhora.Models.Reports", b =>
                {
                    b.HasOne("GolAhora.Models.AdminProfile", "admin")
                        .WithMany("reports")
                        .HasForeignKey("idAdmin")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("admin");
                });

            modelBuilder.Entity("GolAhora.Models.Reservation", b =>
                {
                    b.HasOne("GolAhora.Models.ClientProfile", "client")
                        .WithMany("reservations")
                        .HasForeignKey("idClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolAhora.Models.Court", "court")
                        .WithMany("reservations")
                        .HasForeignKey("idCourt")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolAhora.Models.Payments", "payment")
                        .WithOne("reservation")
                        .HasForeignKey("GolAhora.Models.Reservation", "idPayment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("client");

                    b.Navigation("court");

                    b.Navigation("payment");
                });

            modelBuilder.Entity("GolAhora.Models.Result", b =>
                {
                    b.HasOne("GolAhora.Models.Match", "match")
                        .WithOne("result")
                        .HasForeignKey("GolAhora.Models.Result", "idResults")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("match");
                });

            modelBuilder.Entity("GolAhora.Models.Team", b =>
                {
                    b.HasOne("GolAhora.Models.ClientProfile", "captain")
                        .WithMany("teamsCaptain")
                        .HasForeignKey("clientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("captain");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GolAhora.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GolAhora.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolAhora.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GolAhora.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GolAhora.Models.League", b =>
                {
                    b.HasOne("GolAhora.Models.Competence", null)
                        .WithOne()
                        .HasForeignKey("GolAhora.Models.League", "idCompetence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GolAhora.Models.Tournament", b =>
                {
                    b.HasOne("GolAhora.Models.Competence", null)
                        .WithOne()
                        .HasForeignKey("GolAhora.Models.Tournament", "idCompetence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GolAhora.Models.AdminProfile", b =>
                {
                    b.Navigation("reports");
                });

            modelBuilder.Entity("GolAhora.Models.Class", b =>
                {
                    b.Navigation("assistances");

                    b.Navigation("clients");
                });

            modelBuilder.Entity("GolAhora.Models.ClientProfile", b =>
                {
                    b.Navigation("assistances");

                    b.Navigation("payments");

                    b.Navigation("reservations");

                    b.Navigation("teamsCaptain");
                });

            modelBuilder.Entity("GolAhora.Models.Competence", b =>
                {
                    b.Navigation("games");

                    b.Navigation("teams");
                });

            modelBuilder.Entity("GolAhora.Models.Court", b =>
                {
                    b.Navigation("classes");

                    b.Navigation("disponibilities");

                    b.Navigation("matches");

                    b.Navigation("reservations");
                });

            modelBuilder.Entity("GolAhora.Models.CourtType", b =>
                {
                    b.Navigation("courts");
                });

            modelBuilder.Entity("GolAhora.Models.Discounts", b =>
                {
                    b.Navigation("payments");
                });

            modelBuilder.Entity("GolAhora.Models.Match", b =>
                {
                    b.Navigation("result")
                        .IsRequired();
                });

            modelBuilder.Entity("GolAhora.Models.Payments", b =>
                {
                    b.Navigation("competenceTeams");

                    b.Navigation("receipt")
                        .IsRequired();

                    b.Navigation("reservation")
                        .IsRequired();
                });

            modelBuilder.Entity("GolAhora.Models.PersonalClubProfile", b =>
                {
                    b.Navigation("adminProfile");

                    b.Navigation("employeeProfile");

                    b.Navigation("professorProfile");
                });

            modelBuilder.Entity("GolAhora.Models.ProfessorProfile", b =>
                {
                    b.Navigation("certifications");

                    b.Navigation("classes");
                });

            modelBuilder.Entity("GolAhora.Models.Team", b =>
                {
                    b.Navigation("competences");

                    b.Navigation("localMatches");

                    b.Navigation("players");

                    b.Navigation("visitorMatches");
                });

            modelBuilder.Entity("GolAhora.Models.User", b =>
                {
                    b.Navigation("clientProfile");

                    b.Navigation("personalClubProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
